# Site settings
title: Joules
description: >
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
baseurl: "/joules" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package-lock.json, package.json, bower_components, bower.json, README.md]

campaign-link: link