# Site settings
title: Joules
description: >
  Enter this exclusive competition for a chance to win a £4,000 luxury family holiday with Secret Escapes and £2,000 to spend with Joules.
baseurl: "/joules" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package-lock.json, package.json, bower_components, bower.json, README.md]

campaign-link: https://www.joules.com/win?utm_source=acquisition&utm_medium=partnerships&utm_campaign=secret-escapes&mch=acquisition&mcpt=partnerships&mcpn=secret-escapes
joules-link: https://www.joules.com/?utm_source=acquisition&utm_medium=partnerships&utm_campaign=secret-escapes&mch=acquisition&mcpt=partnerships&mcpn=secret-escapes